Final/Final/Controllers/CheckoutController.cs
using Final.Models;
using MyDLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace Final.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        ProductEntities storeDB = new ProductEntities();
        const string PromoCode = "FREE";
        //
        // GET: /Checkout/
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index()
        {
            return View();
        }
        //
        // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var model = new DonDatHang() { 
                ddh_UserName = user.UserName,
                ddh_Phone = user.PhoneNumber,
                ddh_Email = user.Email,
                ddh_FullName = user.FullName,
                ddh_Address = user.Address
            };

            return View(model);
        }
        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new DonDatHang();
            TryUpdateModel(order);

            try
            {
                
                order.ddh_UserName = User.Identity.Name;
                order.ddh_Date = DateTime.Now;

                //Save Order
                storeDB.DonDatHangs.Add(order);
                storeDB.SaveChanges();
                //Process the order
                var cart = ShoppingCart.GetCart(this.HttpContext);
                cart.CreateOrder(order);

                return RedirectToAction("Complete",
                    new { id = order.ddh_ID });
                
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }
        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = storeDB.DonDatHangs.Any(
                o => o.ddh_ID == id &&
                o.ddh_UserName == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
	}
}

Final/Final/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyDLL;
using Final.Models;
using Final.ViewModels;

namespace Final.Controllers
{
    public class GioHangController : Controller
    {
        private ProductEntities storeDB = new ProductEntities();

        // GET: /GioHang/
        public ActionResult Index()
        {
            ViewBag.Title = "MobileCenter";
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // POST: /Store/AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id, string action, string controller)
        {
            // Retrieve the album from the database
            var addedPhone = storeDB.Phones
                .Single(phone => phone.p_ID == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedPhone);
            // Go back to the main store page for more shopping
            return RedirectToAction(action, controller, new { area = "" });
        }
        //
        // AJAX: //GioHang/UpdateCart
        [HttpPost]
        public ActionResult UpdateCart(int id, int count)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            
            // Get the name of the phone to display confirmation
            string phoneName = storeDB.GioHangs
               .Single(item => item.gh_recordID == id).Phone.p_Name;
            // update from cart
            int itemCount = cart.UpdateQuantity(id,count);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(phoneName) +
                    " has been updated from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // AJAX: /GioHang/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the phone to display confirmation
            string phoneName = storeDB.GioHangs
                .Single(item => item.gh_recordID == id).Phone.p_Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message

            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(phoneName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
    }
}

Final/Final/Controllers/MobileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyDLL;
using System.Web.Mvc.Html;
using System.Web.Helpers;
using PagedList;

namespace Final.Controllers
{
    public class MobileController : Controller
    {
        private ProductEntities db = new ProductEntities();

        // GET: /Mobile/
        public ActionResult Index(int id, int? page)   // id is maker; example 1 is Iphone
        {
            var phones = from s in db.Phones select s;

            ViewBag.currentID = id;

            switch (id)
            {
                case 1:
                    phones = phones.Where(s => s.p_Maker.ToUpper().Contains("iphone".ToUpper()));
                    break;
                case 2:
                    phones = phones.Where(s => s.p_Maker.ToUpper().Contains("ss".ToUpper()));
                    break;
                case 3:
                    phones = phones.Where(s => s.p_Maker.ToUpper().Contains("nokia".ToUpper()));
                    break;
                case 4:
                    phones = phones.Where(s => s.p_Maker.ToUpper().Contains("htc".ToUpper()));
                    break;
                case 5:
                    phones = phones.Where(s => s.p_Maker.ToUpper().Contains("lg".ToUpper()));
                    break;
                case 6:
                    phones = phones.Where(s => s.p_Maker.ToUpper().Contains("oppo".ToUpper()));
                    break;
                default:
                    break;

            }
            phones = phones.OrderBy(s => s.p_ID);
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(phones.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Mobile/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = db.Phones.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // GET: /Mobile/Create
        public ActionResult Create()
        {
            ViewBag.p_DeID = new SelectList(db.DetailPhones, "De_ID", "De_Maker");
            return View();
        }

        // POST: /Mobile/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="p_ID,p_DeID,p_Name,p_Status,p_Price,p_Maker,p_Image,p_hot")] Phone phone)
        {
            if (ModelState.IsValid)
            {
                db.Phones.Add(phone);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.p_DeID = new SelectList(db.DetailPhones, "De_ID", "De_Maker", phone.p_DeID);
            return View(phone);
        }

        // GET: /Mobile/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = db.Phones.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            ViewBag.p_DeID = new SelectList(db.DetailPhones, "De_ID", "De_Maker", phone.p_DeID);
            return View(phone);
        }

        // POST: /Mobile/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="p_ID,p_DeID,p_Name,p_Status,p_Price,p_Maker,p_Image,p_hot")] Phone phone)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phone).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.p_DeID = new SelectList(db.DetailPhones, "De_ID", "De_Maker", phone.p_DeID);
            return View(phone);
        }

        // GET: /Mobile/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = db.Phones.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // POST: /Mobile/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Phone phone = db.Phones.Find(id);
            db.Phones.Remove(phone);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        public ActionResult AddComment(string noidung, int idsp)
        {
            var comment = new BinhLuan()
            {
                cmt_spID = idsp,
                cmt_noidung = noidung
            };
            db.BinhLuans.Add(comment);
            db.SaveChanges();
            return Json(new { success = true });
        }
        public ActionResult DanhSachBinhLuan(int idsp)
        { 
            var listcmt = db.BinhLuans.Where(b => b.cmt_spID == idsp).ToList();
            return Json(listcmt);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult DanhsachSanPham(int? page)
        {
            var phones = from s in db.Phones select s;
            phones = phones.OrderBy(s => s.p_ID);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(phones.ToPagedList(pageNumber, pageSize));
        }
    }
}

Final/Final/Views/GioHang/Index.cshtml
@model Final.ViewModels.ShoppingCartViewModel

@{

    ViewBag.Title = "MobileCenter";
}
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/Default.css" rel="stylesheet" />
    <link href="~/Content/js-image-slider.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/js-image-slider.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"
            type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            function update(){
                alert("haha");
                // Get the id from the link
                var recordToUpdate = $(this).attr("data-id");
                var number = document.getElementById("count-" + recordToUpdate).value;
                if (recordToDelete != '') {
                    // Perform the ajax post
                    $.post("/GioHang/UpdateCart", { "id": recordToUpdate, "count": number },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            
                            $("#cart-total").text(data.CartTotal);
                        });
                }
            }
            // Document.ready -> link up remove event handler
            $(".RemoveLink").click(function () {
                // Get the id from the link
                var recordToDelete = $(this).attr("data-id");
                if (recordToDelete != '') {
                    // Perform the ajax post
                    $.post("/GioHang/RemoveFromCart", { "id": recordToDelete },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            if (data.ItemCount == 0) {
                                $('#row-' + data.DeleteId).fadeOut('slow');
                            } else {
                                $('#item-count-' + data.DeleteId).text(data.ItemCount);
                            }
                            $('#cart-total').text(data.CartTotal);
                            
                            alert(data.Message);
                            $('#cart-status').text('Cart (' + data.CartCount + ')');
                        });
                }
            });
        });
    </script>

</head>
<body>
    <div id="main_container">
        <div class="top_bar">
            <div class="top_search">
                <div class="search_text"><a href="http://all-free-download.com/free-website-templates/">Advanced Search</a></div>
                <input type="text" class="search_input" name="search" />
                <input type="image" src="~/Image/search.gif" class="search_bt" />
            </div>
        </div>
        <div id="header">
            <div id="sliderFrame">
                <div id="slider">
                    <img src="~/Image/slider-1.png" />
                    <img src="~/Image/slider-2.png" />
                    <img src="~/Image/slider-3.png" />
                    <img src="~/Image/slider-5.png" />
                </div>
                <!--Custom navigation buttons on both sides-->
                <div class="group-Wrapper">
                    <a onclick="imageSlider.previous()" class="group-Prev"></a>
                    <a onclick="imageSlider.next()" class="group-Next"></a>
                </div>
            </div>
            <!-- end of oferte_content-->
        </div>
        <div id="search">
            @using (Html.BeginForm("Index", "Home"))
            {
                <div class="left_menu_corner"></div>
                <ul class="menu">
                    <li class="submenu">
                        Hãng sản xuất: @Html.DropDownList("Maker", new SelectList(new List<Object>
                {
                    new {value = "All", text = "All"},
                    new {value = "iphone", text = "Iphone"},
                    new {value = "ss", text = "Samsung"},
                    new {value = "nokia", text = "Nokia"},
                    new {value = "htc", text = "HTC"},
                    new {value = "lg", text = "LG"},
                    new {value = "oppo", text = "Oppo"}
                },
                "value",
                "text",
                "All"))

                    </li>
                    <li class="divider"></li>

                    <li class="submenu">
                        Hệ Điều Hành: @Html.DropDownList("OS", new SelectList(new List<Object>
                {
                    new {value = "All", text = "All"},
                    new {value = "Android", text = "Android"},
                    new {value = "iOS", text = "IOS"},
                    new {value = "Windows", text = "Windows Phone"}
                },
                "value",
                "text",
                "All"))
                    </li>
                    <li class="divider"></li>
                    <li class="submenu">

                        Mức Giá: @Html.DropDownList("Price", new SelectList(new List<Object>
                {
                    new {value = 0, text = "All"},
                    new {value = 2, text = "Khoảng 2 triệu"},
                    new {value = 4, text = "Khoảng 4 triệu"},
                    new {value = 6, text = "Khoảng 6 triệu"},
                    new {value = 8, text = "Khoảng 8 triệu"},
                    new {value = 10, text = "Khoảng 10 triệu"},
                    new {value = 12, text = "Khoảng 12 triệu"},
                    new {value = 14, text = "Khoảng 14 triệu"},
                    new {value = 16, text = "Khoảng 16 triệu"},
                    new {value = 18, text = "Khoảng 18 triệu"},
                    new {value = 20, text = "Khoảng 20 triệu"}
                },
                "value",
                "text",
                0))
                    </li>
                    <li class="divider"></li>
                    <li class="submenu">
                        <input type="image" src="~/Image/search.gif" />
                    </li>
                </ul>
                <div class="right_menu_corner"></div>
            }
        </div>
        <div id="main_content">
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <div id="menu_tab">
                    <div class="left_menu_corner"></div>
                    <ul class="menu">
                        <li><a href="#" class="nav1"> Home</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav2">Products</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav3">Specials</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav4">My account</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav4">Sign Up</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav5">Shipping</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav6">Contact Us</a></li>
                        <li class="divider"></li>

                    </ul>
                    <div class="right_menu_corner"></div>
                </div>
            }
            <div class="left_content">
                <div class="title_box">Categories</div>
                <ul class="left_menu">
                    <li class="odd">@Html.ActionLink("Apple", "Index", "Mobile", new { id = 1 }, null)</li>
                    <li class="even">@Html.ActionLink("Samsung", "Index", "Mobile", new { id = 2 }, null)</li>
                    <li class="odd">@Html.ActionLink("Nokia", "Index", "Mobile", new { id = 3 }, null)</li>
                    <li class="even">@Html.ActionLink("HTC", "Index", "Mobile", new { id = 4 }, null)</li>
                    <li class="odd">@Html.ActionLink("LG", "Index", "Mobile", new { id = 5 }, null)</li>
                    <li class="even">@Html.ActionLink("Oppo", "Index", "Mobile", new { id = 6 }, null)</li>
                </ul>
                <div class="title_box">Special Products</div>
                <div class="border_box">
                    <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                    <div class="product_img"><a href="details.html"><img src="images/laptop.png" alt="" border="0" /></a></div>
                    <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                </div>
                <div class="title_box">Newsletter</div>
                <div class="border_box">
                    <input type="text" name="newsletter" class="newsletter_input" value="your email" />
                    <a href="http://all-free-download.com/free-website-templates/" class="join">join</a>
                </div>
            </div>

            <!-- end of left content -->
            <div class="center_content">
                <div class="center_title_bar">Giỏ hàng</div>
                <p class="button">
                    @Html.ActionLink("Checkout >>", "AddressAndPayment", "Checkout")
                </p>
                <div id="update-message">
                </div>
                <table class="cart">
                    <tr>
                        <th>
                            Phone Name
                        </th>
                        <th>
                            Price (each)
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.CartItems){
                        <tr id="row-@item.gh_recordID">
                            <td>
                                <a href="@Url.Action("Details", "Mobile", new { id = item.Phone.p_ID })"><img src="@Url.Content(@item.Phone.p_Image)" alt="Image phone" width="70" height="140" /></a>
                                @Html.ActionLink(item.Phone.p_Name, "Details", "Mobile", new { id = item.gh_spID }, null)
                            </td>
                            <td>
                                @item.Phone.p_Price
                            </td>
                            <td id="item-count-@item.gh_recordID">
                                <input type="text" id="count-@item.gh_recordID" onblur="update()" value="@item.gh_soluong"/>
                            </td>
                            <td>
                                <a href="#" class="RemoveLink" data-id="@item.gh_recordID">
                                    Remove from cart
                                </a>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            Total
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            @Model.CartTotal vnđ
                        </td>
                    </tr>
                </table>
                <div class="clear"></div>
                <!-- end of center content -->
            </div>
            <br />

            <p style="clear:both"></p>

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - CellMobile</p>
            </footer>
        </div>
    </div>
</body>
</html>